services:
  - type: web
    name: yuksi-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        sync: false          # you paste value in dashboard
      - key: JWT_SECRET_KEY
        sync: false
    plan: free               # 750 h/month, sleeps after 15 min